### ISSUE TITLE
Error while downloading data using azcopy

### ISSUE THREAD

**Issue by rookie0607** [microsoft/NOTSOFAR1-Challenge#29] opened 2024-02-23 07:13 UTC

**Comment by rookie0607** [comment] 2024-02-23 07:13
I am using azcopy to download the simulation data used for css training keeps interrupting, ERROR LOG:.
2024-02-22 14:21:28,912 [INFO] [azure_storage] Downloading to temp dir first: /tmp/tmp9mivr0cw
INFO: scanning...
INFO: will not process any empty folders, as the source and/or target does not support full folders

Task 4d0542a2-a3a6-e844-6c3e-d8367fb18524 started
Log file located at /root/.azcopy/4d0542a2-a3a6-e844-6c3e-d8367fb18524.log

19.6 %, 1963 Done, 0 Failed, 8037 Pending, 0 Skipped, 10000 Total (scanning...) , 2-sec Throughput (Mb/s): 81.9549
Failed to execute replication command due to error: unable to start job due to error: unable to list file due to reason Read tcp x.x.x.x:x->X.X.X.X:443: Read: Connection was reset by peer.

**Comment by nidleo** [comment] 2024-02-23 10:39
Thanks for your interest in our challenge.

If you share the script you ran we'll try to reproduce the issue.
In the meantime, please try calling azcopy command directly:
`azcopy copy https://notsofarsa.blob.core.windows.net/css-datasets/v1.5/200hrs/train <destination> --recursive`

Note that the 200 hour training set requires about 1TB. Make sure you have enough disk space and a stable connection.

**Comment by rookie0607** [comment] 2024-02-24 15:54
> azcopy copy https://notsofarsa.blob.core.windows.net/css-datasets/v1.5/200hrs/train <destination> --recursive

According to your command, I still received the same error.
erro log:
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 3ca4fc71-013b-5149-7f2d-6cf0398cb350 has started
Log file is located at: /home/.azcopy/3ca4fc71-013b-5149-7f2d-6cf0398cb350.log

22.6 %, 2296 Done, 0 Failed, 7704 Pending, 0 Skipped, 10000 Total (scanning...), 2-sec Throughput (Mb/s): 79.8252
failed to perform copy command due to error: cannot start job due to error: cannot list files due to reason read tcp x.x.x.x:x->20.157.50.176:443: read: connection reset by peer.

**Comment by nidleo** [comment] 2024-02-25 08:48
Thanks for trying again. I wasn't able to reproduce the issue.
Could you share your azcopy version, os version, and the log file at `/home/.azcopy/3ca4fc71-013b-5149-7f2d-6cf0398cb350.log`?

**Comment by rookie0607** [comment] 2024-02-25 10:01
> Thanks for trying again. I wasn't able to reproduce the issue. Could you share your azcopy version, os version, and the log file at `/home/.azcopy/3ca4fc71-013b-5149-7f2d-6cf0398cb350.log`?

[Uploading 3ca4fc71-013b-5149-7f2d-6cf0398cb350.log…]()

**Comment by rookie0607** [comment] 2024-02-25 10:03
> Thanks for trying again. I wasn't able to reproduce the issue. Could you share your azcopy version, os version, and the log file at `/home/.azcopy/3ca4fc71-013b-5149-7f2d-6cf0398cb350.log`?

[3ca4fc71-013b-5149-7f2d-6cf0398cb350.log](https://github.com/microsoft/NOTSOFAR1-Challenge/files/14395958/3ca4fc71-013b-5149-7f2d-6cf0398cb350.log)

**Comment by nidleo** [comment] 2024-02-29 13:19
Closing since this specific issue seems to be resolved with downloading through Azure Storage Explorer:

- Open storage explorer, click "Open connect dialog", then "Blob container or directory".
- Select "anonymously (my blob container allows public access)", paste the url and click "connect". e.g. url=`https://notsofarsa.blob.core.windows.net/css-datasets/v1.5/200hrs/train`.
- You can then download the different folders or individual files.

**Closed by nidleo** 2024-02-29 13:19 UTC
